In [1]:
import numpy as np

# Valid sudoku

In [71]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [72]:
c = np.sum(s,axis=1)
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For rows it is valid")

For rows it is valid


In [73]:
r = np.sum(s,axis=0)
for i in r:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For columns it is valid")

For columns it is valid


In [74]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


# General Questions

In [75]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [76]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [77]:
#Find the average age of students.
slice = data[:,0:1]
avg_age = round(np.mean(slice))
print("The average age of students :",avg_age)

The average age of students : 18


In [78]:
#Extract Math marks of all students.

math_marks = data[:,1:2]
math_marks

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [79]:
#Find the highest Science mark.

round(np.max(data[:2]))

92

In [80]:
#Get details of the student who scored more than 90 in Math.

data[data[:,1]>90]

array([[19, 92, 88]])

In [81]:
#Increase Math marks of all students by 5.
data[:,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [82]:
result = data[:,1:2]+5
result

array([[90],
       [97],
       [81],
       [70],
       [95]])

In [83]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [84]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [85]:
#Get data of students who scored at least 80 in both subjects.
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [86]:
data[ (data[:,1]>=80) & (data[:,2]>=80) ]

array([[19, 92, 88],
       [20, 90, 85]])

In [87]:
#Replace all Science marks < 75 with 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [88]:
data[:,2][data[:,2]<75]=0 
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])