# Basic Array Creation

In [113]:
import numpy as np

In [119]:
# same data type only allowed
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [128]:
# different data type allowed (list)
a = [1,3.4,"hello",True,12,3]
a

[1, 3.4, 'hello', True, 12, 3]

In [133]:
np.array(a)

# here we are putting/changing list to array 
# instead of error it convereted all data type to 'String' if string not present then to float and if not float then integer


array(['1', '3.4', 'hello', 'True', '12', '3'], dtype='<U32')

In [134]:
b = [1,3.4,True,12,3]
c = np.array(b)
c

array([ 1. ,  3.4,  1. , 12. ,  3. ])

In [135]:
# vectors : are something whhich is one dimensional (ek hein row ke andar sab kuch) 
# matrix : are somethibg which has multiple rows and columsn (2 dimensional) but 'List' does not support multi-dimension

l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [136]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array generation function

In [138]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [145]:
#arr = np.zeros(6) # this vector 
arr = np.zeros((6,6)) # this matrix (rows*columns)
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [148]:
# ones
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [155]:
# to know what a function does just enter shift + tab

arr = np.linspace(1,50,8)
arr

array([ 1.,  8., 15., 22., 29., 36., 43., 50.])

# Random Generation Function

In [160]:
#Normalization
np.random.rand(10)
# generates vector

array([0.23951697, 0.04610519, 0.36128068, 0.42989494, 0.86074437,
       0.50637766, 0.60759882, 0.86695111, 0.67646369, 0.7777535 ])

In [161]:
# Standarization -3 to 3 lies values
np.random.randn(10)

array([ 0.3697166 , -1.71445295, -1.46809679,  0.77542017,  0.66877618,
        0.64271185,  1.68492137, -1.81353688, -0.29585981, -0.13363318])

In [169]:
np.random.randint(5) # this generates single random numbers everytime you run this cell between 0-5

4

In [172]:
np.random.randint(1,10,5) # 1-low,10-high,5 size of array

array([2, 3, 9, 5, 7], dtype=int32)

# Array Attributes

In [174]:
arr = np.array([[1,2,3],[5,6,7],[8,9,10]])
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [175]:
arr.shape

(3, 3)

In [176]:
arr.size

9

In [177]:
arr.dtype

dtype('int64')

# Array Methods

In [178]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [180]:
#arr.min()
arr.max()

np.int64(10)

In [181]:
arr.sum()

np.int64(51)

In [182]:
# suppose you want to have sum rowwise or columnwise 
# for column (Y-axis) axis = 0
np.sum(arr,axis=0)

array([14, 17, 20])

In [184]:
# for rows axis=1
np.sum(arr,axis=1)

array([ 6, 18, 27])

In [185]:
# mean
arr.mean()

np.float64(5.666666666666667)

In [186]:
# standard deviation
arr.std()

np.float64(2.9814239699997196)

In [187]:
# find out max number index and min too
arr.argmax()

np.int64(8)

In [191]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [190]:
arr.argmin()

np.int64(0)

# Reshaping and resizing of Vectors

In [205]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [206]:
# you have to convert the above vector into 2D
arr.reshape(6,5)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# Array Indexing and Slicing 

In [207]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [208]:
arr[9]

np.int64(20)

In [209]:
arr[2:6]

array([13, 14, 15, 16])

In [210]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [211]:
arr[2::4]

array([13, 17])

# Numpy indexing and slicing of matrix

In [212]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [214]:
arr[1] # 1st index row indexing starts from 0,1,2..

array([ 6,  7,  8,  9, 10])

In [218]:
# column slicing
arr[:,0]

array([ 1,  6, 11, 16, 21, 26])

In [220]:
# slicing specific portion
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [224]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [226]:
# first 3 columns
slice = arr[:,0:3]
slice

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

# BOOLEAN INDEXING

In [227]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [228]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [229]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Array operations

# Arithmetic Operations

In [232]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7,8,9])
a1+a2

array([ 6,  8, 10, 12, 14])

# Broadcasting

In [235]:
# broadcasting is when you have multiple elements and you want to add a number to each and every element
# then we use broadcasting as follow

l = [10,20,30,40]
arr = np.array(l)

In [234]:
arr+10

array([20, 30, 40, 50])

In [240]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [241]:
np.arange(1,21).reshape(4,5)*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

# Deep copy and shallow copy

In [244]:
# whenever you are dealing with array then any changes you made in array, array creates a new
# space for that in RAM,it does not affect the original array unlike list
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [245]:
slice = a[:5]
slice = slice*5
slice

array([ 5, 10, 15, 20, 25])

In [246]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix Operations

In [255]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [256]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [258]:
a @ b

array([[19, 22],
       [43, 50]])

# Advance Array Manipulation

stacking array

In [259]:
# you cannot stack matrix 

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [260]:
# horizonatl stak
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [261]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [279]:
c = np.arange(1,21).reshape(5,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [280]:

np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

In [281]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [286]:
np.vsplit(c,5)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]])]